### PR TITLE
JBIDE-19262 CordovaSim: Fixing widget is disposed after skin changing

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by maxandersen** [comment]
+1

**Comment by ibuziuk** [comment]
@gorkem Max have applied the fix to 4.3.0.Alpha1x. So I guess all we need is to rise `master` branch to `jbosstools-4.3.0.Alpaha1x` and push it

**Comment by gorkem** [comment]
@ibuziuk you should now be able to merge these yourself... So I will let you do the honors.

**Comment by ibuziuk** [comment]
@gorkem thanks
So, I will apply it now

**Pull request merged**
