### PR TITLE
Renaming from o.j.t.vpe.cordovasim to o.j.t.cordovasim

### PR DESCRIPTION
**Pull request by kmarmaliykov**

### CODE REVIEW

**Comment by maxandersen** [comment]
is there any reason for doing such a rename that makes backports and/or p2 updates more complicated ?

**Comment by kmarmaliykov** [comment]
Browsersim and cordovasim are not parts of vpe, but they containing vpe naming. That's incorrect.
This will make updates more complicated, but is it a problem for Alpha releases?

**Comment by maxandersen** [comment]
its a problem for backporting changes and for if you have any settings based on the bundle id.

**Comment by kmarmaliykov** [comment]
yes, we should also check central cause we can install cordovasim with adding hybrid mobile project.

**Comment by ibuziuk** [comment]
Looks good. I have tested it locally and everything seems to be just fine. Pushing to master

**Pull request merged**
