### PR TITLE
JBIDE-19091 CordovaSim: Fixing LiveReload after pressing 'Refresh' button from the 'Platform' toolbar

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by maxandersen** [comment]
do we know why the NPE happens ? i.e. why it would be called when browser is null/disposed ?

**Comment by ibuziuk** [comment]
@maxandersen apparently, there is a problem with browser disposal for the case with ripple's browser reload. Trying to tackle the problem

**Comment by ibuziuk** [comment]
@maxandersen  PR was updated. I have slightly changed the way of RippleInjector initialization.
Could you +1 ?

**Comment by ibuziuk** [comment]
@maxandersen if you are ok with the PR we will release it to master and I will cherry-pick it to 4.2.x

**Comment by maxandersen** [comment]
+1

**Comment by ibuziuk** [comment]
@gorkem could you please apply

**Pull request merged**
